services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb_otus
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=otus_webtours
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_otus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      # Автоимпорт подключения к базе данных (Data Source)
      - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      # Автоимпорт конфигурации дашбордов
      - ./grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      # Сам файл дашборда
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: